// lib/tarot.ts

import { TarotCard } from "@/types/tarot";

export const TAROT_CARDS: ReadonlyArray<TarotCard> = [
    {
        id: 0,
        numeral: "0",
        name: "The Fool",
        arcana: "major",
        summary: "beginnings, adventure, spontaneity, innocence, freedom",
        description: "",
        question: "What new beginnings or adventures are you ready to embark on",
        planet: "Uranus ♅",
        element: "Air 🌬️",
        zodiac: "",
    },
    {
        id: 1,
        numeral: "I",
        name: "The Magician",
        arcana: "major",
        summary: "manifestation, communication, inherent abilities",
        description: "",
        question:
            "How can you effectively utilize your skills and resources to manifest your goals",
        planet: "Mercury ☿️",
        element: "Air 🌬️",
        zodiac: "",
    },

    {
        id: 2,
        numeral: "II",
        name: "The High Priestess",
        arcana: "major",
        summary: "mystery, intuition, divine feminine",
        description: "",
        question:
            "How can you connect more deeply with your intuition and inner wisdom",
        planet: "Moon 🌚",
        element: "Water 🌊",
        zodiac: "",
    },
    {
        id: 3,
        numeral: "III",
        name: "The Empress",
        arcana: "major",
        summary: "Love, creativity, abundance",
        description: "",
        question: "In what areas can you foster growth and creativity",
        planet: "Venus ♀",
        element: "Earth 🪴",
        zodiac: "",
    },
    {
        id: 4,
        numeral: "IV",
        name: "The Emperor",
        arcana: "major",
        summary: "Self discipline, order, focus, strategy",
        description: "",
        question:
            "Where in your life could a structured and authoritative approach be beneficial",
        planet: "Mars ♂",
        element: "Fire 🔥",
        zodiac: "Aries",
    },
    {
        id: 5,
        numeral: "V",
        name: "The Hierophant",
        arcana: "major",
        summary: "tradition, conformity, guidance, wisdom, belief",
        description: "",
        question:
            "How can traditional wisdom or guidance play a role in your current situation",
        planet: "",
        element: "Earth 🪴",
        zodiac: "Taurus",
    },
    {
        id: 6,
        numeral: "VI",
        name: "The Lovers",
        arcana: "major",
        summary: "choice, love, harmony, relationships, values",
        description: "",
        question:
            "What choices can you make to bring greater harmony and alignment in your relationships and values",
        planet: "",
        element: "Air 🌬️",
        zodiac: "Gemini",
    },
    {
        id: 7,
        numeral: "VII",
        name: "The Chariot",
        arcana: "major",
        summary: "control, willpower, victory, determination, direction",
        description: "",
        question:
            "How can you assert control and direction to overcome current challenges",
        planet: "Moon",
        element: "Water 🌊",
        zodiac: "Cancer 🦀",
    },
    {
        id: 8,
        numeral: "VIII",
        name: "Strength",
        arcana: "major",
        summary: "courage, patience, control, compassion, inner strength",
        description: "",
        question:
            "How can you utilize your inner strength and compassion to address current challenges",
        planet: "",
        element: "Fire 🔥",
        zodiac: "Leo",
    },
    {
        id: 9,
        numeral: "IX",
        name: "The Hermit",
        arcana: "major",
        summary: "introspection, solitude, guidance, wisdom, self-reflection",
        description: "",
        question:
            "How can a period of introspection and solitude benefit you at this time",
        planet: "",
        element: "Earth 🪴",
        zodiac: "Virgo",
    },
    {
        id: 10,
        numeral: "X",
        name: "The Wheel of Fortune",
        arcana: "major",
        summary: "cycles, change, luck, fate, opportunity",
        description: "",
        question: "How can you best adapt to the current changes in your life",
        planet: "Jupiter ♃",
        element: "Fire 🔥",
        zodiac: "",
    },
    {
        id: 11,
        numeral: "XI",
        name: "Justice",
        arcana: "major",
        summary: "fairness, balance, accountability, truth, law",
        description: "",
        question:
            "How can you ensure fairness and balance in your current decisions",
        planet: "",
        element: "Air 🌬️",
        zodiac: "Libra",
    },
    {
        id: 12,
        numeral: "XII",
        name: "The Hanged Man",
        arcana: "major",
        summary: "surrender, new perspectives, patience, sacrifice, letting go",
        description: "",
        question:
            "How can adopting a new perspective or pausing for reflection benefit your current situation",
        planet: "Neptune",
        element: "Water 🌊",
        zodiac: "",
    },
    {
        id: 13,
        numeral: "XIII",
        name: "Death",
        arcana: "major",
        summary: "transformation, endings, change, renewal, transition",
        description: "",
        question: "What changes can you embrace for personal growth and renewal",
        planet: "Pluto ♇",
        element: "Water 🌊",
        zodiac: "Scorpio ♏",
    },
    {
        id: 14,
        numeral: "XIV",
        name: "Temperance",
        arcana: "major",
        summary: "balance, moderation, patience, harmony, integration",
        description: "",
        question:
            "Where in your life can you apply balance and moderation for greater harmony",
        planet: "",
        element: "Fire 🔥",
        zodiac: "Sagittarius",
    },
    {
        id: 15,
        numeral: "XV",
        name: "The Devil",
        arcana: "major",
        summary: "bondage, materialism, temptation, obsession, limitation",
        description: "",
        question:
            "What can you liberate yourself from to regain control over your life",
        planet: "",
        element: "Earth 🪴",
        zodiac: "Capricorn",
    },
    {
        id: 16,
        numeral: "XVI",
        name: "The Tower",
        arcana: "major",
        summary: "upheaval, disruption, revelation, change, liberation",
        description: "",
        question:
            "How can you use disruptive changes as opportunities for growth and rebuilding",
        planet: "Mars ♂",
        element: "Fire 🔥",
        zodiac: "",
    },
    {
        id: 17,
        numeral: "XVII",
        name: "The Star",
        arcana: "major",
        summary: "hope, inspiration, serenity, renewal, optimism",
        description: "",
        question:
            "Where can you find hope and inspiration in your current situation",
        planet: "",
        element: "Air 🌬️",
        zodiac: "Aquarius",
    },
    {
        id: 18,
        numeral: "XVIII",
        name: "The Moon",
        arcana: "major",
        summary: "illusion, intuition, uncertainty, subconscious, mystery",
        description: "",
        question:
            "How can you use your intuition to navigate through current uncertainties",
        planet: "",
        element: "Water 🌊",
        zodiac: "Pisces 🎏",
    },
    {
        id: 19,
        numeral: "XIX",
        name: "The Sun",
        arcana: "major",
        summary: "joy, success, clarity, vitality, positivity",
        description: "",
        question:
            "How can you embrace and share the joy and success in your life right now",
        planet: "Sun ☀️",
        element: "Fire 🔥",
        zodiac: "",
    },
    {
        id: 20,
        numeral: "XX",
        name: "Judgement",
        arcana: "major",
        summary: "rebirth, reflection, awakening, judgment, transformation",
        description: "",
        question:
            "What recent realizations can lead to your transformation and renewal",
        planet: "Pluto ♇",
        element: "Fire 🔥",
        zodiac: "",
    },
    {
        id: 21,
        numeral: "XXI",
        name: "The World",
        arcana: "major",
        summary: "completion, fulfillment, achievement, harmony, travel",
        description: "",
        question:
            "How can you celebrate and integrate the lessons from your recent achievements",
        planet: "Saturn 🪐",
        element: "Earth 🪴",
        zodiac: "",
    },
    {
        id: 22,
        numeral: "",
        name: "Ace of Cups",
        arcana: "minor",
        summary: "emotional beginnings, love, joy, intuition, creativity",
        description: "",
        question: "What new emotional experiences are emerging for you",
        planet: "",
        element: "Water 🌊",
        zodiac: "Cancer, Scorpio, Pisces",
    },
    {
        id: 23,
        name: "Two of Cups",
        numeral: "",
        arcana: "minor",
        summary: "partnership, connection, harmony, unity, attraction",
        description: "",
        question: "How can you strengthen and celebrate your important connections",
        planet: "Venus ♀",
        element: "Water 🌊",
        zodiac: "Cancer 🦀",
    },
    {
        id: 24,
        numeral: "",
        name: "Three of Cups",
        arcana: "minor",
        summary: "celebration, friendship, community, joy, togetherness",
        description: "",
        question:
            "How can you enjoy and share the joy with your community or friends",
        planet: "Mercury ☿️",
        element: "Water 🌊",
        zodiac: "Cancer 🦀",
    },
    {
        id: 25,
        numeral: "",
        name: "Four of Cups",
        arcana: "minor",
        summary:
            "apathy, contemplation, missed opportunities, disinterest, introspection",
        description: "",
        question:
            "What unnoticed opportunities or blessings can you become more aware of",
        planet: "Moon 🌚",
        element: "Water 🌊",
        zodiac: "Cancer 🦀",
    },
    {
        id: 26,
        numeral: "",
        name: "Five of Cups",
        arcana: "minor",
        summary: "loss, regret, disappointment, reflection, moving on",
        description: "",
        question:
            "How can you move past regret and focus on the positive aspects still present in your life",
        planet: "Mars ♂",
        element: "Water 🌊",
        zodiac: "Scorpio ♏",
    },
    {
        id: 27,
        numeral: "",
        name: "Six of Cups",
        arcana: "minor",
        summary: "nostalgia, memories, innocence, reunion, childhood",
        description: "",
        question: "How can your past positively influence your present",
        planet: "Sun ☀️",
        element: "Water 🌊",
        zodiac: "Scorpio ♏",
    },
    {
        id: 28,
        numeral: "",
        name: "Seven of Cups",
        arcana: "minor",
        summary: "choices, illusions, fantasy, confusion, opportunity",
        description: "",
        question:
            "How can you make clear and grounded choices among the options presented to you",
        planet: "Venus ♀",
        element: "Water 🌊",
        zodiac: "Scorpio ♏",
    },
    {
        id: 29,
        numeral: "",
        name: "Eight of Cups",
        arcana: "minor",
        summary: "departure, letting go, search, emotional transition, abandonment",
        description: "",
        question:
            "What might you need to leave behind to pursue greater fulfillment",
        planet: "Saturn 🪐",
        element: "Water 🌊",
        zodiac: "Pisces 🎏",
    },
    {
        id: 30,
        numeral: "",
        name: "Nine of Cups",
        arcana: "minor",
        summary:
            "satisfaction, fulfillment, contentment, wish-fulfillment, gratitude",
        description: "",
        question:
            "What aspects of your life bring you profound satisfaction and gratitude",
        planet: "Jupiter ♃",
        element: "Water 🌊",
        zodiac: "Pisces ♓",
    },
    {
        id: 31,
        numeral: "",
        name: "Ten of Cups",
        arcana: "minor",
        summary: "happiness, harmony, family, fulfillment, joy",
        description: "",
        question:
            "How can you cultivate and appreciate the joy and harmony in your relationships",
        planet: "Mars ♂",
        element: "Water 🌊",
        zodiac: "Pisces 🎏",
    },
    {
        id: 32,
        numeral: "",
        name: "Page of Cups",
        arcana: "minor",
        summary:
            "sensitivity, intuition, creativity, opportunity, emotional exploration",
        description: "",
        question: "How can you explore and express your emotions and creativity",
        planet: "",
        element: "Earth of Water",
        zodiac: "",
    },
    {
        id: 33,
        numeral: "",
        name: "Knight of Cups",
        arcana: "minor",
        summary: "romance, charm, idealism, artistic, messenger",
        description: "",
        question: "Where can you follow your heart more passionately in your life",
        planet: "",
        element: "Fire of Water 🌊",
        zodiac: "Aquarius",
    },
    {
        id: 34,
        numeral: "",
        name: "Queen of Cups",
        arcana: "minor",
        summary: "empathy, intuition, compassion, emotional stability, healing",
        description: "",
        question:
            "How can you use your empathy and intuition to nurture yourself and others",
        planet: "",
        element: "Water of Water 🌊",
        zodiac: "Cancer 🦀",
    },
    {
        id: 35,
        numeral: "",
        name: "King of Cups",
        arcana: "minor",
        summary: "emotional balance, diplomacy, maturity, understanding, counsel",
        description: "",
        question:
            "How can you lead with emotional wisdom and balance in your current situation",
        planet: "",
        element: "Air of Water 🌊",
        zodiac: "Scorpio ♏",
    },
    {
        id: 36,
        numeral: "",
        name: "Ace of Pentacles",
        arcana: "minor",
        summary: "opportunity, prosperity, new ventures, growth, material gain",
        description: "",
        question:
            "What new financial or material opportunities are opening up for you",
        planet: "",
        element: "Earth 🪴",
        zodiac: "",
    },
    {
        id: 37,
        numeral: "",
        name: "Two of Pentacles",
        arcana: "minor",
        summary:
            "balance, adaptability, multitasking, resource management, flexibility",
        description: "",
        question:
            "How can you effectively manage and balance your current responsibilities and resources",
        planet: "Jupiter ♃",
        element: "Earth 🪴",
        zodiac: "Capricorn",
    },
    {
        id: 38,
        numeral: "",
        name: "Three of Pentacles",
        arcana: "minor",
        summary: "teamwork, collaboration, skill, craftsmanship, achievement",
        description: "",
        question:
            "How can you collaborate effectively with others to achieve your shared goals",
        planet: "Mars ♂",
        element: "Earth 🪴",
        zodiac: "Capricorn",
    },
    {
        id: 39,
        numeral: "",
        name: "Four of Pentacles",
        arcana: "minor",
        summary: "security, control, stability, possessiveness, conservation",
        description: "",
        question:
            "How can you balance the need for financial security with flexibility and openness to change",
        planet: "Sun ☀️",
        element: "Earth 🪴",
        zodiac: "Capricorn",
    },
    {
        id: 40,
        numeral: "",
        name: "Five of Pentacles",
        arcana: "minor",
        summary: "hardship, lack, isolation, worry, adversity",
        description: "",
        question:
            "How can you find the support you need during this challenging time",
        planet: "Mercury ☿️",
        element: "Earth 🪴",
        zodiac: "Taurus",
    },
    {
        id: 41,
        numeral: "",
        name: "Six of Pentacles",
        arcana: "minor",
        summary: "generosity, charity, fairness, sharing, balance",
        description: "",
        question:
            "How can you practice giving and receiving with balance and fairness",
        planet: "Moon 🌚",
        element: "Earth 🪴",
        zodiac: "Taurus",
    },
    {
        id: 42,
        numeral: "",
        name: "Seven of Pentacles",
        arcana: "minor",
        summary: "patience, investment, assessment, reward, growth",
        description: "",
        question:
            "How can you assess and plan for continued growth in your current endeavors",
        planet: "Saturn 🪐",
        element: "Earth 🪴",
        zodiac: "Taurus",
    },
    {
        id: 43,
        numeral: "",
        name: "Eight of Pentacles",
        arcana: "minor",
        summary: "craftsmanship, skill development, diligence, quality, dedication",
        description: "",
        question:
            "How can you further develop and refine your skills in your current pursuits",
        planet: "Sun",
        element: "Earth 🪴",
        zodiac: "Virgo",
    },
    {
        id: 44,
        numeral: "",
        name: "Nine of Pentacles",
        arcana: "minor",
        summary: "abundance, luxury, self-sufficiency, reward, comfort",
        description: "",
        question:
            "How can you savor and appreciate your accomplishments and the comfort they bring",
        planet: "Venus",
        element: "Earth 🪴",
        zodiac: "Virgo",
    },
    {
        id: 45,
        numeral: "",
        name: "Ten of Pentacles",
        arcana: "minor",
        summary: "legacy, wealth, family, establishment, fulfillment",
        description: "",
        question: "How are you building and sharing a lasting legacy",
        planet: "Mercury",
        element: "Earth 🪴",
        zodiac: "Virgo",
    },
    {
        id: 46,
        numeral: "",
        name: "Page of Pentacles",
        arcana: "minor",
        summary: "opportunity, study, ambition, diligence, pragmatism",
        description: "",
        question:
            "What new learning or practical opportunities are you eager to explore",
        planet: "",
        element: "Earth in Earth 🪴",
        zodiac: "",
    },
    {
        id: 47,
        numeral: "",
        name: "Knight of Pentacles",
        arcana: "minor",
        summary:
            "reliability, productivity, thoroughness, responsibility, perseverance",
        description: "",
        question:
            "Where can your steadfast and meticulous approach bring you success",
        planet: "",
        element: "Fire in Earth 🪴",
        zodiac: "Leo",
    },
    {
        id: 48,
        numeral: "",
        name: "Queen of Pentacles",
        arcana: "minor",
        summary: "nurturing, practicality, comfort, resourcefulness, stability",
        description: "",
        question:
            "How can you use your nurturing and practical abilities to create stability and comfort in your life and for those around you?",
        planet: "",
        element: "Water in Earth 🪴",
        zodiac: "Capricorn",
    },
    {
        id: 49,
        numeral: "",
        name: "King of Pentacles",
        arcana: "minor",
        summary: "prosperity, business acumen, reliability, success, stability",
        description: "",
        question:
            "How can you harness your abilities and resources for continued prosperity and stability?",
        planet: "",
        element: "Air in Earth 🪴",
        zodiac: "",
    },
    {
        id: 50,
        numeral: "",
        name: "Ace of Swords",
        arcana: "minor",
        summary: "clarity, breakthrough, truth, intellect, communication",
        description: "",
        question:
            "How can you harness clarity and decisiveness in your current situation",
        planet: "",
        element: "Air 🌬",
        zodiac: "Gemini, Libra, Aquarius",
    },
    {
        id: 51,
        numeral: "",
        name: "Two of Swords",
        arcana: "minor",
        summary: "indecision, balance, choices, stalemate, compromise",
        description: "",
        question:
            "How can you find balance and clarity to make a thoughtful decision in your current dilemma",
        planet: "Moon",
        element: "Air 🌬️",
        zodiac: "Libra",
    },
    {
        id: 52,
        numeral: "",
        name: "Three of Swords",
        arcana: "minor",
        summary: "heartache, sorrow, emotional pain, separation, release",
        description: "",
        question:
            "How can you navigate through your current emotional challenges to find healing and understanding",
        planet: "Saturn",
        element: "Air 🌬️",
        zodiac: "Libra",
    },
    {
        id: 53,
        numeral: "",
        name: "Four of Swords",
        arcana: "minor",
        summary: "rest, recovery, contemplation, peace, respite",
        description: "",
        question:
            "How can you best use a period of rest to rejuvenate and gain clarity",
        planet: "Jupiter",
        element: "Air 🌬️",
        zodiac: "Libra",
    },
    {
        id: 54,
        numeral: "",
        name: "Five of Swords",
        arcana: "minor",
        summary: "conflict, tension, defeat, ego, compromise",
        description: "",
        question:
            "How can you navigate conflicts in a way that minimizes harm and fosters resolution",
        planet: "Venus",
        element: "Air 🌬️",
        zodiac: "Aquarius",
    },
    {
        id: 55,
        numeral: "",
        name: "Six of Swords",
        arcana: "minor",
        summary: "transition, change, movement, release, escape",
        description: "",
        question:
            "How are you moving towards healing and stability in your current circumstances",
        planet: "Mercury",
        element: "Air 🌬️",
        zodiac: "Aquarius",
    },
    {
        id: 56,
        numeral: "",
        name: "Seven of Swords",
        arcana: "minor",
        summary: "strategy, caution, cunning, deceit, prudence",
        description: "",
        question:
            "How can you approach your current challenges with smart strategy and awareness",
        planet: "Moon",
        element: "Air 🌬️",
        zodiac: "Aquarius",
    },
    {
        id: 57,
        numeral: "",
        name: "Eight of Swords",
        arcana: "minor",
        summary:
            "restriction, limitation, self-imposed barriers, helplessness, perspective",
        description: "",
        question:
            "How can you break free from self-imposed limitations to see new possibilities",
        planet: "Jupiter",
        element: "Air 🌬️",
        zodiac: "Gemini",
    },
    {
        id: 58,
        numeral: "",
        name: "Nine of Swords",
        arcana: "minor",
        summary: "anxiety, worry, fear, guilt, mental anguish",
        description: "",
        question:
            "How can you address and manage the worries and fears that are currently affecting your peace of mind",
        planet: "Mars",
        element: "Air 🌬️",
        zodiac: "Gemini",
    },
    {
        id: 59,
        numeral: "",
        name: "Ten of Swords",
        arcana: "minor",
        summary: "betrayal, loss, finality, collapse, release",
        description: "",
        question:
            "How can you embrace the end of a challenging phase and prepare for a new beginning",
        planet: "Sun",
        element: "Air 🌬️",
        zodiac: "Gemini",
    },
    {
        id: 60,
        numeral: "",
        name: "Page of Swords",
        arcana: "minor",
        summary: "curiosity, vigilance, honesty, intellect, communication",
        description: "",
        question: "What new learning or intellectual pursuits are you exploring",
        planet: "",
        element: "Earth in Air 🌬️",
        zodiac: "",
    },
    {
        id: 61,
        numeral: "",
        name: "Knight of Swords",
        arcana: "minor",
        summary: "action, ambition, aggression, directness, determination",
        description: "",
        question: "How can you channel your energy and determination effectively",
        planet: "",
        element: "Fire in Air 🌬️",
        zodiac: "Gemini",
    },
    {
        id: 62,
        numeral: "",
        name: "Queen of Swords",
        arcana: "minor",
        summary: "clarity, independence, insight, communication, perception",
        description: "",
        question:
            "How can you utilize your confidence and charisma in your current endeavors",
        planet: "",
        element: "Water in Air 🌬️",
        zodiac: "",
    },
    {
        id: 63,
        numeral: "",
        name: "King of Swords",
        arcana: "minor",
        summary: "authority, rationality, integrity, discipline, fairness",
        description: "",
        question:
            "How can your wisdom and fairness influence your current decisions",
        planet: "",
        element: "Air in Air 🌬️",
        zodiac: "",
    },
    {
        id: 64,
        numeral: "",
        name: "Ace of Wands",
        arcana: "minor",
        summary: "inspiration, potential, creativity, enthusiasm, initiative",
        description: "",
        question:
            "What new creative or energetic endeavor are you inspired to begin",
        planet: "",
        element: "Fire 🔥",
        zodiac: "Aries, Leo, Sagittarius",
    },
    {
        id: 65,
        numeral: "",
        name: "Two of Wands",
        arcana: "minor",
        summary: "planning, future, decision, discovery, direction",
        description: "",
        question: "What future possibilities are you currently considering",
        planet: "Mars",
        element: "Fire 🔥",
        zodiac: "Aries",
    },
    {
        id: 66,
        numeral: "",
        name: "Three of Wands",
        arcana: "minor",
        summary: "expansion, foresight, progress, exploration, opportunity",
        description: "",
        question: "What progress are you anticipating in your plans",
        planet: "Sun",
        element: "Fire 🔥",
        zodiac: "Aries",
    },
    {
        id: 67,
        numeral: "",
        name: "Four of Wands",
        arcana: "minor",
        summary: "celebration, joy, harmony, stability, homecoming",
        description: "",
        question: "What recent achievements can you celebrate",
        planet: "Venus",
        element: "Fire 🔥",
        zodiac: "Aries",
    },
    {
        id: 68,
        numeral: "",
        name: "Five of Wands",
        arcana: "minor",
        summary: "competition, conflict, struggle, challenge, adversity",
        description: "",
        question: "How can you navigate current conflicts constructively",
        planet: "Saturn",
        element: "Fire 🔥",
        zodiac: "Leo",
    },
    {
        id: 69,
        numeral: "",
        name: "Six of Wands",
        arcana: "minor",
        summary: "victory, success, recognition, achievement, pride",
        description: "",
        question: "What recent achievement deserves recognition",
        planet: "Jupiter",
        element: "Fire 🔥",
        zodiac: "Leo",
    },
    {
        id: 70,
        numeral: "",
        name: "Seven of Wands",
        arcana: "minor",
        summary: "defense, resilience, courage, challenge, perseverance",
        description: "",
        question: "Where do you need to stand firm in your beliefs or decisions",
        planet: "Mars",
        element: "Fire 🔥",
        zodiac: "Leo",
    },
    {
        id: 71,
        numeral: "",
        name: "Eight of Wands",
        arcana: "minor",
        summary: "speed, movement, progress, action, rapid change",
        description: "",
        question: "How can you best harness the current momentum in your life?",
        planet: "Mercury",
        element: "Fire 🔥",
        zodiac: "Sagittarius",
    },
    {
        id: 72,
        numeral: "",
        name: "Nine of Wands",
        arcana: "minor",
        summary: "resilience, persistence, boundaries, courage, endurance",
        description: "",
        question: "Where do you need to maintain your resolve and perseverance",
        planet: "Moon 🌚",
        element: "Fire 🔥",
        zodiac: "Sagittarius",
    },
    {
        id: 73,
        numeral: "",
        name: "Ten of Wands",
        arcana: "minor",
        summary: "burden, responsibility, overcommitment, strain, perseverance",
        description: "",
        question: "Where can you lighten your load or seek support",
        planet: "Saturn 🪐",
        element: "Fire 🔥",
        zodiac: "Sagittarius",
    },
    {
        id: 74,
        numeral: "",
        name: "Page of Wands",
        arcana: "minor",
        summary: "enthusiasm, exploration, discovery, freedom, potential",
        description: "",
        question: "What new adventure or creative pursuit excites you",
        planet: "",
        element: "Earth in Fire 🔥",
        zodiac: "",
    },
    {
        id: 75,
        numeral: "",
        name: "Knight of Wands",
        arcana: "minor",
        summary: "passion, adventure, impulsiveness, action, energy",
        description: "",
        question: "Where can your passion and energy be best directed now",
        planet: "",
        element: "Fire in Fire 🔥",
        zodiac: "",
    },
    {
        id: 76,
        numeral: "",
        name: "Queen of Wands",
        arcana: "minor",
        summary: "charisma, confidence, independence, vitality, determination",
        description: "",
        question:
            "How can you utilize your confidence and charisma in your current endeavors",
        planet: "",
        element: "Water in Fire 🔥",
        zodiac: "",
    },
    {
        id: 77,
        numeral: "",
        name: "King of Wands",
        arcana: "minor",
        summary: "leadership, vision, boldness, charisma, inspiration",
        description: "",
        question:
            "Where can you demonstrate strong leadership and vision in your life",
        planet: "",
        element: "Air in Fire 🔥",
        zodiac: "",
    },
] as const;
